### PR TITLE
add hmset command support

### PR DESCRIPTION
**Pull request by Stonewuu**

### CODE REVIEW

**Comment by Stonewuu** [comment]
I hava already add SQL Test, see here

https://github.com/Stonewuu/flink-connector-redis/blob/322d37f87ec73140b47cb1722a5119c1a6162378/src/test/java/org/apache/flink/streaming/connectors/redis/table/SQLInsertTest.java#L97-L120

**Comment by jeff-zou** [comment]
Thanks for you PR,
BTW,Please submit your next PR to dev branch.

石头 ***@***.***> 于2024年4月22日周一 21:58写道：

**Comment by jeff-zou** [comment]
1.4.2 had released for support hmset， thanks for your contribution.
```
<dependency>
    <groupId>io.github.jeff-zou</groupId>
    <artifactId>flink-connector-redis</artifactId>
    <!-- 没有单独引入项目依赖Lettuce netty-transport-native-epoll依赖时 -->
    <!--            <classifier>jar-with-dependencies</classifier>-->
    <version>1.4.2</version>
</dependency>
```

**Comment by Stonewuu** [comment]
> 1.4.2 had released for support hmset， thanks for your contribution.
> 
> ```
> <dependency>
>     <groupId>io.github.jeff-zou</groupId>
>     <artifactId>flink-connector-redis</artifactId>
>     
>     
>     <version>1.4.2</version>
> </dependency>
> ```

thanks!🥳

**Pull request merged**
